name: Cache

on:
  push:
    branches:
      - 'canary*'
  workflow_dispatch:

concurrency: cache

jobs:
  cache:
    name: Cache
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
